import React, { useEffect, useState } from 'react';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth } from '../lib/firebase';
import { subscribeToApplicantApplication } from '../services/applicationService';
import type { GirlfriendApplication } from '../types/application';
import { STAGE_CONFIG, STATUS_CONFIG } from '../types/application';
import { useNavigation } from '../context/NavigationContext';

export const ApplicantDashboardPage: React.FC = () => { const {navigate}=useNavigation(); const [app,setApp]=useState<GirlfriendApplication|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [signingOut,setSigningOut]=useState(false); useEffect(()=>onAuthStateChanged(auth,user=>{if(!user){navigate('login');return} return subscribeToApplicantApplication(user.uid,(data)=>{setApp(data);setLoading(false)},err=>{setError(err.message);setLoading(false)})}),[navigate]); const handleLogout=async()=>{setSigningOut(true);setError('');try{await signOut(auth);navigate('login')}catch(err:any){setError(err?.message||'Unable to log out. Please try again.');setSigningOut(false)}}; if(loading)return <div className="p-12 text-center">Loading your application…</div>; if(error||!app)return <div className="p-12 text-center">{error||'No application was found for this account.'}</div>; const stage=STAGE_CONFIG[app.currentStage]; const date=app.createdAt?.toDate?.()?.toLocaleDateString?.()||'Recently'; return <section className="mx-auto max-w-4xl px-5 py-16"><div className="flex items-start justify-between border-b border-[#d5cec0] pb-7"><div><p className="font-mono text-[11px] tracking-[.15em] text-[#a83328]">YOUR APPLICATION</p><h1 className="mt-3 font-editorial text-5xl">Hello, {app.preferredName}.</h1></div><button onClick={handleLogout} disabled={signingOut} className="text-sm underline disabled:opacity-50">{signingOut?'Logging out…':'Log out'}</button></div><div className="grid gap-0 border-b border-[#d5cec0] py-7 sm:grid-cols-3"><div><span className="text-xs text-[#736d62]">APPLICATION ID</span><p className="mt-1 font-mono text-sm">{app.id}</p></div><div><span className="text-xs text-[#736d62]">STATUS</span><p className="mt-1 text-sm">{STATUS_CONFIG[app.status].label}</p></div><div><span className="text-xs text-[#736d62]">COMPATIBILITY</span><p className="mt-1 text-sm">{app.compatibilityScore}/100</p></div></div>{app.adminMessage&&<aside className="my-8 border-l-2 border-[#a83328] pl-5"><p className="text-xs font-semibold tracking-[.12em] text-[#a83328]">A NOTE FROM ALEXANDER</p><p className="mt-2 text-sm leading-6">{app.adminMessage}</p></aside>}<h2 className="mt-10 font-editorial text-3xl">Application progress</h2><ol className="mt-6 border-t border-[#d5cec0]">{Object.entries(STAGE_CONFIG).map(([key,value])=><li key={key} className={`grid grid-cols-[3rem_1fr_auto] border-b border-[#d5cec0] py-4 text-sm ${value.order<=stage.order?'text-[#171716]':'text-[#9b9487]'}`}><span className="font-mono text-xs">0{value.order}</span><span>{value.label}</span>{key===app.currentStage&&<span className="text-xs text-[#a83328]">CURRENT</span>}</li>)}</ol><p className="mt-8 text-xs text-[#736d62]">Submitted {date} · Last updated automatically.</p></section> };
